### ISSUE TITLE
Create nightly builds page

### ISSUE THREAD

**Issue by wolf-sigma** [Herdinger/EmulationStation#10]
Need the ability to post nightly (really builds of current commit from master) builds for:
- Linux x86_64 (Ubuntu 14.04)
- OSX (El Capitan)
- ARM6_RPI1 (NOOBS)
- ARM7_RP2 (RetroPie)
- Windows 10 x86

**Comment by wolf-sigma** [comment]
Currently have Buildbot running on my network for all but Windows. Will work on publishing binaries and logs to a web server for public consumption.

**Comment by wolf-sigma** [comment]
Windows is finally working now! See README.md for download URL.

**Comment by blm07** [comment]
I get the 3 error boxes saying that DLL files are missing when I try to run this and the other previous versions of emulationstation. The original ES didn't do that. I've tried installing it and the vcruntime thing, but they are still "missing" when I try to run it.

**Comment by wolf-sigma** [comment]
Are you running emulationstation.exe or the install? You will need to overwrite the installed .exe in program files if you don't use the install (i.e. these builds don't replace the need for the dependent DLLs).

**Comment by blm07** [comment]
I tried both, I tried replacing just the exe and installing it again, and both ways it says the same thing.

**Comment by wolf-sigma** [comment]
Ok, thanks. What DLLs does it say are missing?

**Comment by blm07** [comment]
vcruntime140d.dll
msvcp140d.dll
ucrtbased.dll

**Comment by wolf-sigma** [comment]
Ah. We're shipping the VC13 redistributable, but since we're compiling with MVC2015 now, we need to do the 14 ones. I'll fix the installer to do 14 instead of 13.

You can get around this with this: https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by wolf-sigma** [comment]
Updated the installer with the new distributable. Would love if you tested that to see if it fixes yours.

**Comment by blm07** [comment]
It has the same error, am I supposed to restart or is there something simple that I could be missing? Restarting hasn't helped before.

**Comment by wolf-sigma** [comment]
No, that's not it. I just stood up a fresh Windows instance, and am able to reproduce it. There's something on the Visual Studio 2015 that you need. Just need to figure it out :)

**Comment by wolf-sigma** [comment]
Ok. GOT IT. The new installer should work just fine now.

For the record, the problem was two-fold. The first issue is you do need both the 2013 and 2015 distributables (probably because some of the DLLs are built with VC2013) and you need to build the code with a "Release" target.

**Comment by blm07** [comment]
Sweet, it works, and I'm looking forward to seeing this great front end evolving.
