### ISSUE TITLE
Can we contribute OSX compilation fixes to RetroPie?

### ISSUE THREAD

**Issue by seriema** [Herdinger/EmulationStation#14]
Thanks for getting EmulationStation to compile on OSX!

I was wondering if it's ok to share it with the RetroPie team? I forked their project and cherry-picked some of your commits to get it to compile on my mac. With your permission I'd like to create a PR to RetroPie/EmulationStation with this:
https://github.com/seriema/EmulationStation/commits/osx-compilation-fixes

**Comment by wolf-sigma** [comment]
No issues here. I am looking at pulling in most of RetroPie's fixes too, but I have no issue moving the OSX builds to RetroPie too.

**Comment by seriema** [comment]
Cool!

I actually tried adding all your stuff onto RetroPie and it was pretty easy.
https://github.com/seriema/EmulationStation/commits/herdinger-rebase

So I think you could easily rebase off of them.

**Comment by wolf-sigma** [comment]
Hey @seriema  - I pulled in all of RetroPie's changes...would be nice to get us working on the same repo, but I guess we'll have to just keep rebasing :)
