### ISSUE TITLE
Windows Installer

### ISSUE THREAD

**Issue by brando56894** [Herdinger/EmulationStation#15]
It would be awesome to have a Windows installer, I'm actually a Linux guy but this will be for my Steam Machine (which will sadly run Windows for the time being), and I really have no idea how to compile stuff under Windows, last time I did it was over a decade ago.

**Comment by wolf-sigma** [comment]
It's a pretty big PITA to be honest. We are working on packaging stuff that will help, but progress has been slow. The first step will be to have a nightly section to download binaries from instead of having to compile them.

**Comment by Aloshi** [comment]
If it helps, you can have the old installer scripts I made back when ES first released.

The Windows installer was built with [NSIS](http://nsis.sourceforge.net/Main_Page). To use it, just put the relevant files in the same folder, and run NSIS on `es_installer.nsi`. The files to install are listed in the .nsi file (`File emulationstation.exe`, etc). If you add/remove any, make sure you also update the matching `Delete $INSTDIR\emulationstation.exe` lines for the uninstaller. [Here it is](https://dl.dropboxusercontent.com/u/2816162/es_win_packaging.zip) (along with the old 2.x files from the last installer I built).

**Comment by wolf-sigma** [comment]
This is awesome. I'll build this into our continuous build workflow

**Comment by wolf-sigma** [comment]
Thanks to @Aloshi, I published an install of the latest build to dropbox (soon to be automatically built). Look at the Readme for the link (incase it changes).
