### ISSUE TITLE
Monitor 2

### ISSUE THREAD

**Issue by blm07** [Herdinger/EmulationStation#16]
Can we have the option to display emulation station on another monitor? I use it on my PC hooked up to the TV with HDMI, and it would be nice to either have a option or command line to make it show up on a different monitor.

**Comment by wolf-sigma** [comment]
I think this is a totally fair ask, we just have to figure out how to do it. I'll do some poking and see what I can come up with.

**Comment by blm07** [comment]
Sounds good to me! I'm glad you guys took over this project.

**Comment by wolf-sigma** [comment]
Just committed a change for this (and the binaries built and are on dropbox). You can modify it via the config or in the UI Settings menu. You do have to restart ES at the moment due to where the setting takes effect (very early).
