### ISSUE TITLE
Broken portable setup?

### ISSUE THREAD

**Issue by RJRetro** [Herdinger/EmulationStation#24]
I use a portable setup of ES.  It uses a batch file: `set HOME=%~dp0
emulationstation.exe` and everything works nicely on the old Aloshi version.  But when I put the latest build from dropbox into my setup and run the batch file, I get the message about it not having any systems.  Has something been changed that would prevent a portable setup?  Or do I need to do something else?

**Comment by Herdinger** [comment]
The configuration directory has changed : https://github.com/Herdinger/EmulationStation#configuring

Setting path isn't necessary on Windows any more, just copy your old config to the new location and it should work.

**Comment by RJRetro** [comment]
I'm a bit confused... Do you mean I _have_ to use the new config directory or can I change the config directory with a command in the batch file?  If not, it kinda kills the portable setup.

**Comment by Herdinger** [comment]
Oh sorry I've misread the meaning of the word portable.
Sure thing you're right, I will add an argument for manually specifying the config dir and update the README.

**Comment by wolf-sigma** [comment]
Thanks Herdinger.

While you're in there, I was thinking we should check in the old config location for backwards compatibility. Then if none are found, it can create it in the new location. Does that make sense to you?

**Comment by Herdinger** [comment]
Just pushed the changes, you can either use the old behaviour or explicitly specify a config directory with the --config-directory [path] command line option

**Comment by RJRetro** [comment]
That was quick!  Thanks, it works great.  Didn't have to change anything :D
