### ISSUE TITLE
Linux System shutdown and restart command doesn`t work

### ISSUE THREAD

**Issue by Mernst1** [Herdinger/EmulationStation#42]
When I click the shutdown or also the restart command in the menu Emulationstation just closes.
It doesn`t shutdown or restart the hole System.

**Comment by MCMic** [comment]
From what I’ve seen in emulationstation output it uses sudo on shutdown command.
So you need to give the user emulationstation runs under the right to use sudo shutdown without password.
http://askubuntu.com/questions/159007/how-do-i-run-specific-sudo-commands-without-a-password

**Comment by Mernst1** [comment]
Okay, I tried it again. I wrote in the sudoers file that users can use the shutdown command with root access. But Emulationstation still doesn`t shutdown only closes Emulationstation. When I try it in the terminal with user rights its working. I also tried to change the command in the plattform.cpp from 'sudo shutdown -h now' in 'shutdown -P now' and its not working.
I think the Problem seems to be somewhere in the code.

**Comment by johnodon** [comment]
I am having the same issue compiled on Lubuntu 16.04.  If I try to restart ES or restart/shutdown the system, I am taken back to the desktop.  My local acct has been added to sudoers and it did not help:

sudo sed -i '$ a\retro ALL=(ALL) NOPASSWD:ALL' /etc/sudoers

Stock ES from the PPA works fine (although missing 'Restart ES' option obviously).

**Comment by CaptainBoatCode** [comment]
Fixed it, was working on #37 and found that the functions runShutdownCommand and runRestartCommand where never called. Going to do a pull request with the fix.

However, for the fix to work emulationstation has to be run as root or under permission to reboot or shutdown the system !

See pull-request: https://github.com/Herdinger/EmulationStation/pull/45
