### ISSUE TITLE
Error when compiling on linux

### ISSUE THREAD

**Issue by ghost** [Herdinger/EmulationStation#5]
Hi,

Thank for this fork.

Compilation failed on linux (ubuntu 16.04). I obtain this message :

.../EmulationStation-master/es-core/src/ImageIO.cpp: In static member function ‘static std::vector<unsigned char> ImageIO::loadFromMemoryRGBA32(const unsigned char*, size_t, size_t&, size_t&)’:

.../EmulationStation-master/es-core/src/ImageIO.cpp:46:61: error: ‘memcpy’ was not declared in this scope
       memcpy(tempData + (i \* width \* 4), scanLine, width \* 4);
                                                             ^
.../EmulationStation-master/es-core/src/ImageIO.cpp:39:19: warning: unused variable ‘pitch’ [-Wunused-variable]
      unsigned int pitch = FreeImage_GetPitch(fiBitmap);
                   ^
.../EmulationStation-master/es-core/src/ImageIO.cpp:24:16: warning: unused variable ‘fiConverted’ [-Wunused-variable]
     FIBITMAP \* fiConverted = nullptr;
                ^
es-core/CMakeFiles/es-core.dir/build.make:146: recipe for target 'es-core/CMakeFiles/es-core.dir/src/ImageIO.cpp.o' failed
make[2]: **\* [es-core/CMakeFiles/es-core.dir/src/ImageIO.cpp.o] Error 1
CMakeFiles/Makefile2:194: recipe for target 'es-core/CMakeFiles/es-core.dir/all' failed
make[1]: **\* [es-core/CMakeFiles/es-core.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by Herdinger** [comment]
Im on the go right now so i can't compile, the issue should be fixed tho. Could you try again?

**Comment by ghost** [comment]
ok, it works! thank.
